# Generated by Django 6.0.1 on 2026-01-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(default="#FFFFFF", max_length=9),
        ),
    ]
